### ISSUE TITLE
Depend on spring-cloud-config-client release

### ISSUE THREAD

**Issue by bspaans** [spring-cloud/spring-cloud-starters#12]
Hi, we have been running the spring cloud config setup for a couple of months now, but we discovered some problems today which are caused by an update in the spring-cloud-config-client that introduced a new setting which you need to set to enable the service. 

We don't directly depend on spring-cloud-config-client, but instead use the spring-cloud-starter project; yet we still pulled in these changes. I think the reason for this is that the spring-cloud-starter pom doesn't specify versions for its dependencies, which makes it use the snapshot instead.

I'd like to hear your thoughts on this, but would it be possible to pin the version of spring-cloud-config-client to the latest release (currently 1.0.0.RC1)?

**Comment by dsyer** [comment]
The versions are managed in the parent poms (and they are pinned to RC1 in RC1). How are you configuring your build?

**Comment by dsyer** [comment]
Ping.

**Comment by bspaans** [comment]
Hi, sorry for the late reply -- just got the notification. I set up an empty project and tried to get the RC1 version using:

```
<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter</artifactId>
		<version>1.0.0.RC1</version>
</dependency>
```

..and it pulled in all the right dependencies; I'm not exactly sure anymore why we were seeing the things we saw last week, but I'm suspecting that we might have been depending on the snapshot all along.

Sorry for wasting your time, but thanks for the pointer (and the project!)

Cheers, 
Bart
