### ISSUE TITLE
spring-cloud-starter should not depend on Spring Cloud Config

### ISSUE THREAD

**Issue by ewolff** [spring-cloud/spring-cloud-starters#16]
As pointed out in https://github.com/spring-cloud-samples/eureka/issues/11 spring-cloud-starter depends on spring-cloud-config-client  and therefore on Spring Cloud Config. This should be changed IMHO. Spring has always emphasized choice. There are ways to configure a distributed system of Microservices with other approaches i.e. Ansible or Puppet. The Immutable Servers Pattern even argues that a change to a server should alway lead to a new server being start. In those scenarios Spring Cloud Config is not needed. Therefore I would make it optional and remove the dependency.

**Comment by dsyer** [comment]
But Spring Boot (and starters) are about being opinionated and providing an exit route if you have a different opinion. The opinion being expressed here is that the config server is a good thing, and so we make it easy to use it out of the box. So I would argue that if you don't want the full Monty you can just include the dependencies you need (or exclude the ones you don't).

**Comment by ewolff** [comment]
Spring Boot Actuator is also a good thing but still optional.

**Comment by dsyer** [comment]
It's not optional for a Spring Cloud app (using the starters anyway). That kind of feature has obvious immediate applicability in a distributed system. And so does the config client.
