### ISSUE TITLE
spring-cloud-starter-parent is missing artifacts from mvn repository

### ISSUE THREAD

**Issue by doom777** [spring-cloud/spring-cloud-starters#19]
spring-cloud-starter-aws artifacts reference nonexisting versions of spring-cloud-aws artifacts, causing build failures.
For example, spring-cloud-starter-aws-jdbc:1.0.1.RELEASE depends on spring-cloud-aws-jdbc:1.0.1.RELEASE which does not exist (mvnrepository.com shows a 404)
So too, spring-cloud-starter-aws depends on nonexist autoconfigure and context artifacts.
The workaround for now is to use 1.0.0 versions of spring-cloud-starter artifacts.
The easy solution is publishing the 1.0.1/1.0.2 versions of spring-cloud-aws artifacts to maven repositories.
Side note, maven repositories should anyway block publishes of artifacts with invalid dependencies

see:
http://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-aws/1.0.1.RELEASE.

**Comment by royclarkson** [comment]
Are you trying to build locally? I think the issue may be that you need to specify the settings file:

```
mvn install -s .settings.xml
```

**Comment by dsyer** [comment]
I think this is fixed.
