### ISSUE TITLE
Confusing version numbering

### ISSUE THREAD

**Issue by krishnasdfw** [spring-cloud/spring-cloud-starters#21]
The version numbers like Angel.SR1 etc are very misleading and affects continuity in large enterprise where each version needs approved before that is allowed for use. Don't get what value is added with this type of versioning. It is adding to confusion.

**Comment by spencergibb** [comment]
Why is it misleading?  How does it 'affect continuity'? The [blog post](https://spring.io/blog/2015/06/26/spring-cloud-service-release-angel-sr3#release-train) announcing the release train explains it quite clearly.  We have [more than a dozen](https://github.com/spring-cloud/) separate projects, each with different versions that we are managing. We are also following established release trains from [Spring Data](https://github.com/spring-projects/spring-data-commons/wiki/Release-planning).
