### ISSUE TITLE
License.txt missing

### ISSUE THREAD

**Issue by krishnasdfw** [spring-cloud/spring-cloud-starters#22]
A License.txt in every artifact helps get approvals for that to be made available in internal repositories. Cannot find it in Spring-cloud-starters

**Comment by dsyer** [comment]
Can you find it in all the spring cloud dependencies?

**Comment by dsyer** [comment]
(Not that we shouldn't add one to the starters of course)

**Comment by spencergibb** [comment]
fixed via db8504123fc9efbf49418a9bdc86ff9e04375fbb
