### ISSUE TITLE
Current milestone `Brixton.M1` is referencing wrong spring-cloud-security version

### ISSUE THREAD

**Issue by MichaelF25** [spring-cloud/spring-cloud-starters#25]
How to reproduce:
1. Go to [Spring Initializr] (https://start.spring.io)
2. Generate a Spring Boot 1.3.0.M5 project with `web` and `cloud-security` enabled
3. Build generated project with `mvn package`
4. Maven will report a missing artifact: `Could not find artifact org.springframework.cloud:spring-cloud-starter-security:jar:1.1.0.M1`

The missing artifact is actually not present in `milestones` repository:
https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-security/

**Comment by spencergibb** [comment]
Went through the steps, [spring-cloud-starter-security milestone](https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-security/) was published. This is fixed.
