### ISSUE TITLE
Using spring-cloud-starter-parent for Maven dependency management (as suggested) will change Spring Boot dependencies

### ISSUE THREAD

**Issue by kristofferpeterhansel** [spring-cloud/spring-cloud-starters#34]
So we just had a very strange issue where suddenly a Spring Boot application reverted back to generating incorrect HATEOAS links when running behind a load balancer. A very confusing experience as it was something that had been solved by updating Spring Boot and the Spring HATEOAS versions a while back.

After some digging around we found out that due to having moved to using the suggested dependency management method for including Spring Cloud modules would change the effective POM to be using older versions of a number of libraries - and in our case Spring Web. And it turns out that this method actually introduces a dependency on a specific Spring Boot version as a parent at some point.

So it seems this approach is extremely dangerous as you end up thinking you are using Spring Boot in one version (using it as a parent for your own POM). And then having it overwritten some of those dependencies with versions from whatever version the Spring Cloud release train was build on.

**Comment by spencergibb** [comment]
@kristofferpeterhansel I'm able to choose the version of spring-boot I need (though there is a compatibility matrix: Angel -> boot 1.2.x, Brixton -> boot 1.3.x). Is this still an issue?

**Comment by dsyer** [comment]
Apart from the Angel/Brixton rule, we now (in Brixton) have "pure" BOMs (e.g. spring-cloud-start-dependencies) that you can use in snapshots. We might release them for Angel as well if it helps, which might fix the issue you described, but leave you with the risk that other Angel/1.3 issues will appear at runtime.

**Comment by kristofferpeterhansel** [comment]
Thanks. I guess I'll have to take a look at that when we can actually look at upgrading our applications to the new versions.

One thing though. I guess I am still somewhat confused if you intend to Spring Cloud to be an add-on to Spring Boot or super-set of Spring Boot?

The current project page seems to suggest the latter with the setup instructions. But the text describes it as "tools". And that invokes the idea that I can set up a Spring Boot project like any other and just add this in as I would any of the other Spring projects

**Comment by dsyer** [comment]
I don't think the distinction is valid. Spring Cloud is a set of tools that builds on Spring Boot (so there are going to be version combinations that don't work together). It's not like any other Spring project in that way.

**Comment by kristofferpeterhansel** [comment]
Yes. But how other project suggest you use them is simply add the dependencies to a Spring Boot project. Where Spring Cloud suggest you replace your Spring Boot parent with the Spring Cloud one.

And at least with released versions of Spring Cloud you cannot easily add a version of Spring Cloud to a Spring Boot application without the Spring Boot dependency versions being overwritten - which is what this issue was about.
