### ISSUE TITLE
Adding spring-cloud-starter-config to a boot application stops the app from booting

### ISSUE THREAD

**Issue by mikegehard** [spring-cloud/spring-cloud-starters#35]
Thanks for all of the hard work on Spring Cloud! I am having a problem running with Boot 1.3.0 and Spring Cloud Brixton.M3.

Given I have a Spring Boot Application with Actuator included
When I add spring-cloud-starter-config to that application
Then the application will no longer boot with `./gradlew clean bootRun`
And the error is:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementServerProperties' defined in class path resource [org/springframework/boot/actuate/autoconfigure/ManagementServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
```

Sample app:
https://github.com/mikegehard/bootBugWithSpringCloud

Commits where the app boots:
https://github.com/mikegehard/bootBugWithSpringCloud/commit/c545e437af656e2033305e9a65dffde453c1378c
https://github.com/mikegehard/bootBugWithSpringCloud/commit/3fe1308b5d194dabb60f64a6624f962135d47d1d

Commits where app fails to start:
https://github.com/mikegehard/bootBugWithSpringCloud/commit/9bd90e507d847f7225d397091113732c85686697
https://github.com/mikegehard/bootBugWithSpringCloud/commit/ad2be293aa9b20b22a933e18bfc0e9f53d3a7adb

**Comment by mikegehard** [comment]
Upon doing a bit more digging...

Given I have a boot app from above that won't run
When I add `compile("org.springframework.security:spring-security-config")`
And I add `compile("org.springframework.security:spring-security-web")`
Then the application boots again.

See:
https://github.com/mikegehard/bootBugWithSpringCloud/commit/8225b7263b3993c1fdc28b5ebeb68670acac2ed9

This is a good work around for but it is a bit odd to me that if my application does not have any security requirements now (this app only boots) that I need to add additional dependencies.

As a developer, the Principle of Least Surprise makes me think that my libraries would manage their own dependencies and not force me to add ones that I have no use for.

**Comment by spencergibb** [comment]
Hmm, when I run your app with spring-cloud-starter-config, it works just fine.

The one difference I have in the project I created is that I don't have:
```
        classpath("io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE")
```

But even with it your app runs fine.

**Comment by spencergibb** [comment]
Are you running in an ide?

**Comment by spencergibb** [comment]
So my guess is the the config server you're pointing to has `management.security.*` properties in it.  Which is why it runs fine for me, I don't have a config server running, so no `management.security.*` properties.

See https://github.com/spring-projects/spring-boot/issues/3888

**Comment by mikegehard** [comment]
Thanks @spencergibb for taking a look at this one. 

Yes I had a configuration server running in the background so the application was picking that up and causing the issue mentioned above. When I stop the config server, everything works just fine.

Sorry for the false alarm. :-)
