### ISSUE TITLE
Maven central repo versions

### ISSUE THREAD

**Issue by librucha** [spring-cloud/spring-cloud-starters#36]
Maven central repo resolves version 1.0.2 for spring-cloud-starter-parent as latest but Angel.SR4 is latest by date. I thing the problem is in version "human" naming.

http://search.maven.org/#search%7Cga%7C1%7Cspring-cloud-starter-parent
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.cloud%22%20AND%20a%3A%22spring-cloud-starter-parent%22

**Comment by spencergibb** [comment]
Not sure we can do anything about it. By date the maven central version has it right. We're not going to change our new versioning scheme at this point.
