### ISSUE TITLE
the deployment of Brixton.M4 in the libs-release seems to be broken

### ISSUE THREAD

**Issue by calinvoichita** [spring-cloud/spring-cloud-starters#37]
I tried to update my project to Brixton.M4 and so I updated the spring-cloud-starter-parent version to Brixton.M4. The build failed immediately with "Could not find artifact org.springframework.cloud:spring-cloud-starter-dependencies:pom:Brixton.BUILD-SNAPSHOT". It is strange that M4 is requesting BUILD-SNAPSHOT dependencies. I am using the Spring libs-release as repository.

After a little investigation I noticed that the pom here - https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.M4/ - requests the BUILD-SNAPSHOT which is not available in libs-release.

Also, the tag 'vBrixton.M4' in this repository seems to be correct as it does not depend on BUILD-SNAPSHOT. I am suspecting there was an error during deployment to the repository.

Please advise if I am missing something.

**Comment by spencergibb** [comment]
@calinvoichita nice catch.
the pom contains
```
	<properties>
		<main.basedir>${basedir}/../..</main.basedir>
		<spring-cloud.version>Brixton.BUILD-SNAPSHOT</spring-cloud.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<distributionManagement>
```

**Comment by spencergibb** [comment]
@dsyer can we redeploy that one?

**Comment by calinvoichita** [comment]
I installed the 'vBrixton.M4'  tag in my local repository and I found another issue related to this one - org.springframework.cloud:spring-cloud-parent:pom:1.1.0.M4 - is not available in libs-release. However, this is available in libs-snapshot.

After enabling libs-snapshot on my machine with the 'vBrixton.M4'  tag installed manually, my project compiled with no issue.

To summarize:
- in addition to fixing spring-cloud-starter-parent, spring-cloud-parent:pom:1.1.0.M4 must also be deployed in libs-release

**Comment by spencergibb** [comment]
@calinvoichita `spring-cloud-parent:pom:1.1.0.M4` should _not_ be in libs-release, it is in libs-milestone.

**Comment by spencergibb** [comment]
I guess I'm a bit confused, `spring-cloud-parent:pom:1.1.0.M4` is in libs-milestone-local.

**Comment by spencergibb** [comment]
In fact `spring-cloud-starter-dependencies` was only introduced 5 days ago, no idea how it is showing up in M4, maybe there is a problem with the aggregated repos (libs-snapshot, libs-milestone, libs-release). The pom looks correct in libs-milestone-local. @calinvoichita can you try that repo.

@dsyer @trevormarshall any ideas?

**Comment by dsyer** [comment]
The libs-release is a virtual repository (and includes everything in libs-milestone-local AFAIK). So if the POM is correct in libs-milestone-local and broken in libs-release then it is a problem in our Artifactory instance. We'll have to see if @trevormarshall can flush it out.

**Comment by calinvoichita** [comment]
@spencergibb, you are right. Made a mistake for using release instead of milestone. 

I tried multiple repositories and here is what i found for the `spring-cloud-starter-parent` artifact:
- milestone and libs-milestone-local: contains the correct Brixton.M4 pom (Dec 23rd) and all dependencies are resolved correctly
- libs-milestone: contains faulty Brixton.M4 pom (Jan 8th) that depends on `cloud-starter-dependencies:pom:Brixton.BUILD-SNAPSHOT`


- release, libs-release and libs-release-local all contain the faulty Brixton.M4 pom (Jan 8th)

I think the issue is that the faulty Brixton.M4 was deployed in libs-release-local which should not contain the Brixton.M* branch at all based on my understanding. This would explain the pattern observed above and I think can be solved by removing the `spring-cloud-starter-parent:POM:Brixton.M4` artifact from libs-release-local.

**Comment by travis5555** [comment]
I am having the same issue locally. We have been using Brixton.M4 due to the additional feature support and (seemingly) better alignment with the docs. Will the faulty pom be removed as suggested? Also - any hints around when Brixton.M4 becomes a stable release version would be much appreciated (days/weeks/months?).  Hoping we don't have to move back to Angel.SR4 before our next release. Thanks!

**Comment by spencergibb** [comment]
Ping @trevormarshall.

@travis5555 Brixton will be released in Q1. There may be another milestone before we do a release candidate in Feb.

**Comment by spencergibb** [comment]
The offending pom was removed. Can anyone give it a try?

**Comment by calinvoichita** [comment]
@spencergibb, I tested this with the `libs-milestone` repository (which was broken before) and all the dependencies are resolved correctly. 

The `release`, `libs-release` and `libs-release-local` repositories no longer contain the Brixton.M4 version which is the expected behavior.
