### ISSUE TITLE
Out of date dependencies?

### ISSUE THREAD

**Issue by pacey** [spring-cloud/spring-cloud-starters#38]
Version 1.0.4 depends on outdated versions of hystrix-core and hystrix-javanica. Will these be updated in the spring-cloud-starter-hystrix module?

**Comment by spencergibb** [comment]
They have been updated in Brixton, our next release.

**Comment by pacey** [comment]
Great. Will that end up in maven central?

**Comment by spencergibb** [comment]
Yes, when we release it in Q1
