### ISSUE TITLE
spring-cloud-starter-parent Angel.SR5 incorrect dependency

### ISSUE THREAD

**Issue by nissel** [spring-cloud/spring-cloud-starters#39]
The recently released spring-cloud-starter-parent Angel.SR5, tries to include org.springframework.cloud:spring-cloud-netflix:pom:1.0.5.RELEASE which was never released to maven central.

I guess this is suppose to be 1.0.6.RELEASE

**Comment by dsyer** [comment]
Fixed in Angel.SR6. Thanks.
