### ISSUE TITLE
Wrong Brixton.M? POM in release repository

### ISSUE THREAD

**Issue by sfussenegger** [spring-cloud/spring-cloud-starters#41]
There are two different versions of the Brixton.M4 release in [milestone](http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-parent/Brixton.M4/spring-cloud-starter-parent-Brixton.M4.pom) and [release](http://repo.spring.io/release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.M4/spring-cloud-starter-parent-Brixton.M4.pom).

The one in release seems to be there by accident as it depends on `Brixton.BUILD-SNAPSHOT` and is the latest from master. The reason is probably that the version wasn't properly reset in 1e27a59: version still is `Brixton.M4` but should be `Brixton.BUILD-SNAPSHOT` as it still was in 6ce1be4

**Comment by dsyer** [comment]
@trevormarshall can you delete the one from the "release" (via "libs-release-local") please?

**Comment by dsyer** [comment]
We seem to have stamped this out in M4, but I can still see Brixton.M5 in the release repo (https://repo.spring.io/libs-release-local/org/springframework/cloud/spring-cloud-dependencies/Brixton.M5/) which is wrong. It looks like maybe artifactory is copying it three automatically because I only deployed once and it's identical to the one in the milestone repo.

**Comment by spencergibb** [comment]
The travis build for [`vBrixton.M5`](https://travis-ci.org/spring-cloud/spring-cloud-starters/builds/107215968) is running `./mvnw deploy` and succeeding where previously it [failed](https://travis-ci.org/spring-cloud/spring-cloud-starters/builds/91696106).

**Comment by spencergibb** [comment]
We should use `TRAVIS_TAG` to detect tags and not `deploy`.

> `TRAVIS_TAG`: If the current build for a tag, this includes the tag’s name.

**Comment by dsyer** [comment]
I think this is done (in all the Cloud projects). We  now look at TRAVIS_TAG and TRAVIS_REPO_SLUG to decide whether or not to deploy. We also look at the version to decide if it's a milestone and set the profile.
