### ISSUE TITLE
Spring HTTP Session Error using  Brixton.BUILD-SNAPSHOT, Brixton.M5 and Brixton.M4

### ISSUE THREAD

**Issue by Javierperezmartin** [spring-cloud/spring-cloud-starters#43]
I'm working in a spring-cloud project, composed by 8 spring-boot applications, some of them including web content, and others are just REST APIs.
The system authentication is managed by means of Spring Http Session + Redis.
I'm using the Brixton.BUILD-SNAPSHOT as parent pom.
The system worked fine, but since Friday, 2 Feb 2016, every try to access to any REST API which requires to be authenticated, fails with 403 Forbidden.

After many headaches, I finally replace the JAR libraries from non-working spring-boot applications with the ones from the same spring-boot applications generated before last Friday, 2 Feb 2016. Then all worked fine...

Is there any Brixton Milestone which fix that? YES!! I I compile the same code with:
BUILD-SNAPSHOT...... Fail 403 Forbidden
M5.................................Fail 403 Forbidden
M4.................................Fail 403 Forbidden
M3.................................Works fine!!

- Do you know if there was any change last Friday, 2 Feb 2016 which breaks the Spring-Http-Session-Redis authentication mecanism?
- Do you plan to solve that issue in next milestone version?
- It is expected to be fixed when you launch the GA version?

Best Regards,
Javier Pérez

**Comment by ukjbrown** [comment]
Oddly, I've just tried upgrading from M4 to RC1 and have seen a similar issue. In M4 the session was getting created without issue, since upgrading to RC1 (with no other code changes), no session is created resulting in the 403 forbidden when attempting to login. No cookie is being sent to the client.

**Comment by spencergibb** [comment]
Cookies are no longer forwarded by default with zuul. Are you using zuul? Neither of you has given us much to go on.

**Comment by ukjbrown** [comment]
Apologies, I meant to retract my comment after reading the documentation regarding these headers in Zuul.

**Comment by spencergibb** [comment]
@ukjbrown NP. @Javierperezmartin waiting on more from you then.

**Comment by borlafu** [comment]
Hi all, I'm involved in the OPs project. This is part of a migration to Spring Cloud and I'm still catching up with all the details. However, I can confirm we do use Zuul.

I found these 2 issues which appear to be related on spring-cloud-security:
https://github.com/spring-cloud/spring-cloud-security/issues/41
https://github.com/spring-cloud/spring-cloud-security/issues/92

Can you please point me in the right direction? Should we fix this by configuring or adding some filter in  our Zuul proxy?

I'll come back as soon as I get more info.

**Comment by borlafu** [comment]
I just found it :)
http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_cookies_and_sensitive_headers

> NOTE: this is the default value for `sensitiveHeaders`, so you don’t need to set it unless you want it to be different. N.B. this is new in Spring Cloud Netflix 1.1 (in 1.0 the user had no control over headers and all cookies flow in both directions).

I think the issue can be rejected, as it's working as expected. We have to review our design/configuration before migrating to 1.1 or go back to 1.0 for the time being.

Thanks for the info!
