### ISSUE TITLE
Update to Spring Boot 1.3

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-starters#46]
Currently cannot import spring-cloud-starter-parent as it overrides everything from my parent (spring-boot-starter-parent) and rolls it back to Spring Boot 1.2.3.RELEASE

**Comment by AlexejK** [comment]
Have you tried Brixton milestones, e.g M5? It does not seem to override things for me and allows using Spring Boot 1.3.

**Comment by OrangeDog** [comment]
I was only looking at RELEASE versions, as the naming for the rest was unclear.
Good to know it's being worked on :)

Ideally I don't want to be overriding my existing parent at all, but it doesn't look like maven lets you exclude parents when importing dependencyManagement.
