### ISSUE TITLE
remove reference on not existing spring-cloud-starter-bus-redis in spring-cloud-dependencies

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-starters#47]
see also https://github.com/spring-cloud/spring-cloud-stream/issues/454

**Comment by cforce** [comment]
its seems the same wrong entry for spring-cloud-starter-stream-redis

**Comment by spencergibb** [comment]
There is no reference to `spring-cloud-starter-bus-redis` in this project. It is here https://github.com/spring-cloud/spring-cloud-bus/blob/2a30c12693a9fcee4c71f0ec7f36f0441e43be52/spring-cloud-bus-dependencies/pom.xml#L43
