### ISSUE TITLE
update to spring boot 1.4.0 in snapshot

### ISSUE THREAD

**Issue by xetys** [spring-cloud/spring-cloud-starters#50]
currently the spring-cloud-starter-parent dependencies are pointing to spring boot 1.3.3.RELEASE

so there is currently no way to test 1.4.0 with boot.

I've tried to apply this locally...but both maven and gradle are failing to pick the 1.4.0 instead of 1.3.3...

**Comment by dsyer** [comment]
You shouldn't be using the parent then. These samples [in github](https://github.com/spring-projects/spring-boot/blob/10012cfddc5479ee9a5cbe98bfe4f76483965bd1/spring-boot-cli/src/main/java/org/springframework/boot/cli/command/run/SpringApplicationRunner.java#L82) all work if you change the Boot version to 1.4 (as of yesterday)..
