### ISSUE TITLE
Wrong Quickstart Snippets

### ISSUE THREAD

**Issue by borlafu** [spring-cloud/spring-cloud-starters#52]
The quickstart snippets are wrong in http://projects.spring.io/spring-cloud/#quick-start

According to the [Brixton.RELEASE announcement](https://spring.io/blog/2016/05/11/spring-cloud-brixton-release-is-available), the correct way to bootstrap a Maven project is to inherit from spring-boot-starter-parent and import spring-cloud-dependencies.

So, where the current Maven quickstart is:

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>1.3.3.RELEASE</version>
</parent>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Brixton.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

It should be:

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.3.5.RELEASE</version>
	<relativePath/> <!-- lookup parent from repository -->
</parent>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Brixton.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Notice the change is:
`spring-cloud-starter-parent` -> `spring-boot-starter-parent`
`1.3.3.RELEASE` -> `1.3.5.RELEASE`

I believe the Gradle quickstart is also wrong, as it refers to Spring Boot 1.3.3.RELEASE (instead of 1.3.5.RELEASE) and imports the dependencies from `spring-cloud-starter-parent` instead of `spring-cloud-dependencies`.

BTW: I'm not sure if this is the right project to post this, as the websidte code is not here, but it's the most suitable I found.

**Comment by dsyer** [comment]
Should be fixed now. The code is in spring-projects/spring-cloud.

**Comment by borlafu** [comment]
Thanks!
