### ISSUE TITLE
Region ap-northeast-2(seoul) is not exist.

### ISSUE THREAD

**Issue by okihouse** [spring-cloud/spring-cloud-starters#55]
I'm using `spring-cloud-starter-aws`
```
        <dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-aws</artifactId>
		    <version>1.1.0.RELEASE</version>
		</dependency>
```

This dependency has `aws-java-sdk-core-1.10.30.jar`.

But, 1.10.30 Regions.class is not includes ap-northeast-2.

```
    GovCloud("us-gov-west-1"),
    US_EAST_1("us-east-1"),
    US_WEST_1("us-west-1"),
    US_WEST_2("us-west-2"),
    EU_WEST_1("eu-west-1"),
    EU_CENTRAL_1("eu-central-1"),
    AP_SOUTHEAST_1("ap-southeast-1"),
    AP_SOUTHEAST_2("ap-southeast-2"),
    AP_NORTHEAST_1("ap-northeast-1"),
    SA_EAST_1("sa-east-1"),
    CN_NORTH_1("cn-north-1");
```

So, I check AWS SDK Core module and found it.(AWS SDK for Java 1.11.5)
[Regions.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java)

When Can I use this 1.11.5??

**Comment by spencergibb** [comment]
Please move this to spring-cloud-aws
