### ISSUE TITLE
Add spring-cloud-netflix-hystrix-amqp to the appropriate starter

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-starters#8]

**Comment by dsyer** [comment]
I'm not sure it's worth it since it would be equivalent to simply adding spring-cloud-starter-hystrix and spring-cloud-netflix-hystrix-amqp.

**Comment by mstine** [comment]
Now that I think about it I reckon you're probably right.

Matt Stine
Senior Product Manager
Spring Cloud Services for Pivotal Cloud Foundry

901-493-5546 | Skype: mstine1978 | mstine@pivotal.io

pivotal.io

Pivotal CF - The Future is NOW: Watch and Learn
<https://www.youtube.com/watch?v=a7kYxpSMIME>
