### ISSUE TITLE
the question is that Incompatible versions of springboot and springcloud-eurka

### ISSUE THREAD

**Issue by dyhack** [spring-cloud/spring-cloud-starters#99]
My springboot version is 2.0.3, and my spring-cloud-eurka version is 1.4.5.RELEASE. But when prompted, it prompts java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init> ([Ljava). When I change my version of springboot to 1.5.14, it will be OK.

**Comment by dyhack** [comment]
I use  the Finchley and

**Comment by dyhack** [comment]
my spring boot is 2.0.3

**Comment by ryanjbaxter** [comment]
Those are compatible
